# Generated by Django 2.2.28 on 2022-07-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_test123'),
    ]

    operations = [
        migrations.AddField(
            model_name='test123',
            name='t13654',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
